### ISSUE TITLE
[Bug] Duplicate lines

### ISSUE THREAD

**Issue by artulloss** [natemoo-re/clack#87]
**Environment**

- OS: macOS
- Node Version: v19.1.0
- Package: @clack/prompts
- Package Version: v0.3.0

**Describe the bug**

The terminal duplicates options in a select when moving arrows up and down if the window is too small and the lines try to wrap. More of a rendering bug, because if you expand the terminal, it seems to start working normally, but the duplicates stay and aren't selectable.

**To Reproduce**

https://stackblitz.com/edit/node-omu3tm?file=prompts.js

-  Put several options in a select, then shrink the terminal width so an option splits into multiple lines.

**Expected behavior**

The select should behave normally, moving arrows up and down should not duplicate everything. This seems to be a limitation of the terminal itself, perhaps truncation and an ellipsis of the long options would help.

**Comment by natemoo-re** [comment]
Yep, can confirm. I've implemented a `wrap` utility on [`feat/wrap`](https://github.com/natemoo-re/clack/tree/feat/wrap) but still need to hook this all up in the core library.

**Comment by natemoo-re** [comment]
A quick fix has been released in https://github.com/natemoo-re/clack/pull/98! I'd love to follow-up with a lighter fix, but `wrap-ansi` is thoroughly battle-tested and works well.

I'd also like to update the logic so that each line gets a properly styled prefix, but this at least patches the worst parts of the bug for now.

**Comment by brillout** [comment]
This issue still occurs with scrolling, see https://github.com/bombshell-dev/clack/issues/441.
